---

- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    namespace: bhdicaire
    collection: macTools
    release_tag: "{{ github_tag.split('/')[-1] }}"

  pre_tasks:
    - name: Ensure ANSIBLE_GALAXY_TOKEN is set.
      fail:
        msg: A valid ANSIBLE_GALAXY_TOKEN must be set.
      when: "lookup('env','ANSIBLE_GALAXY_TOKEN') | length == 0"

    - name: Ensure the ~/.ansible directory exists.
      file:
        path: ~/.ansible
        state: directory

    - name: Write the Galaxy token to ~/.ansible/galaxy_token
      copy:
        content: |
          token: {{ lookup('env','ANSIBLE_GALAXY_TOKEN') }}
        dest: ~/.ansible/galaxy_token

  tasks:
    - name: Ensure the galaxy.yml tag is up to date.
      lineinfile:
        path: galaxy.yml
        regexp: "^version:"
        line: 'version: "{{ release_tag }}"'

    - name: Build the collection.
      command: ansible-galaxy collection build

    - name: Publish the collection.
      command: >
        ansible-galaxy collection publish ./{{ namespace }}-{{ collection }}-{{ release_tag }}.tar.gz
